import 'package:hive/hive.dart';

part 'task.g.dart'; // generated by build_runner - do not write this file by hand

// @HiveType marks this class as storable in Hive. typeId must be UNIQUE
// across your whole app - Hive uses it to know how to decode stored bytes.
@HiveType(typeId: 0)
class Task extends HiveObject {
  @HiveField(0)
  String title;

  @HiveField(1)
  bool isDone;

  Task({required this.title, this.isDone = false});
}
